### PR TITLE
Fix blog post opengraph image

### LINKED ISSUE #1220: Fix blog posts opengraph image
https://twitter.com/IncidentsDB/status/1578135108283879424?s=20&t=AWdGs3YmwbqbLIl_hiH7RQ

### PR DESCRIPTION
**Pull request by pdcp1**
Closes #1220

### Steps to test

1. Open preview link https://deploy-preview-1250--staging-aiid.netlify.app
2. Open any blog post
3. Copy the blog post URL. ie: https://deploy-preview-1250--staging-aiid.netlify.app/blog/multilingual-incident-reporting
4. Share the blog post link on
4.1 Twitter
4.2 LinkedIn
4.3 Facebook
5. Check if the image preview is displayed correctly on each post/tweet

### Twitter:

image

### LinkedIn post:

image
 
### Facebook post

image

### CODE REVIEW

File: site/gatsby-site/src/templates/post.js [hunk 1]
```diff
@@ -23,13 +23,21 @@ export default function Post(props) {
 
   let canonicalUrl = config.gatsby.siteUrl;
 
+  const postImage = mdx.frontmatter.image?.childImageSharp?.gatsbyImageData?.images?.fallback?.src;
```
Comment (cesarvarela) [inline site/gatsby-site/src/templates/post.js:26]: so?.much?.optional?.chaining

**Review by cesarvarela — APPROVED** [review]
