### PR TITLE
Fix z-index so tooltips are above

### LINKED ISSUE #2345: Collapsed sidebar tooltip appearing under page content
image

image

image

### PR DESCRIPTION
**Pull request by clari182**
- closes #2345 

Should not break #2164 

https://pr-2803--staging-aiid.netlify.app/

### CODE REVIEW

File: site/gatsby-site/src/components/Layout.js [hunk 1]
```diff
@@ -24,7 +24,7 @@ const Layout = ({ children, className, sidebarCollapsed = false, location }) =>
         <div
           id="content"
           className={
-            'flex flex-grow pt-4 px-4 pb-5 md:px-10 md:pb-10 z-[1] relative flex-1 overflow-clip' +
+            'flex flex-grow pt-4 px-4 pb-5 md:px-10 md:pb-10 z-1 relative flex-1 overflow-clip' +
```
Comment (lmcnulty) [inline site/gatsby-site/src/components/Layout.js:27]: Does z-1 actually do anything? It seems like [Tailwind jumps from z-0 to z-10 for whatever reason](https://tailwindcss.com/docs/z-index).

**Review by lmcnulty — APPROVED** [review]

**Comment by kepae** [comment]
Polite ping on this PR. Good to merge?

**Comment by clari182** [comment]
@kepae yes good to go!
