### PR TITLE
Fix/entities link

### LINKED ISSUE #1436: Cross Link Entities pages and incidents table
The entities here: https://incidentdatabase.ai/apps/incidents/

Should link to their respective entities pages.

### PR DESCRIPTION
**Pull request by clari182**
- resolves #1436

### CODE REVIEW

File: site/gatsby-site/src/components/incidents/IncidentsTable.js [hunk 1]
```diff
@@ -134,19 +155,28 @@ export default function IncidentsTable({ data }) {
...
+            return { name: i.name, url: `/entities/${i.entity_id}` };
+          }),
         Cell: ListCell,
       },
       {
         Header: <Trans>Alleged Harmed or Nearly Harmed Parties</Trans>,
         id: 'AllegedHarmedOrNearlyHarmedParties',
-        accessor: (data) => data.AllegedHarmedOrNearlyHarmedParties.map((i) => i.name),
+        accessor: (data) =>
+          data.AllegedHarmedOrNearlyHarmedParties.map((i) => {
```
Comment (cesarvarela) [inline site/gatsby-site/src/components/incidents/IncidentsTable.js:177]: Missing url here it seems.

**Review by cesarvarela — CHANGES_REQUESTED** [review]
Please add tests.

**Review by cesarvarela — APPROVED** [review]
