### PR TITLE
Fix report ID link

### LINKED ISSUE #1583: Report's title anchor href is missing report number
So instead of only updating the address bar it sends you to the homepage:

image

### PR DESCRIPTION
**Pull request by lmcnulty**
Resolves #1583.

### CODE REVIEW

File: site/gatsby-site/src/components/reports/ReportCard.js [hunk 1]
```diff
@@ -55,11 +54,11 @@ const ReportCard = ({ item, className = '', incidentId }) => {
       >
         <div className="flex items-center w-full justify-between">
           <div>
-            <LocalizedLink to={`#r${item.report_number}`} className="max-w-full cursor-pointer">
+            <a href={`#r${item.report_number}`} className="max-w-full cursor-pointer">
```
Comment (cesarvarela) [inline site/gatsby-site/src/components/reports/ReportCard.js:57]: `LocalizedLink` doesn't handle the hash?

**Comment by cesarvarela** [comment]
Please fix conflicts!

File: site/gatsby-site/src/components/reports/ReportCard.js (hunk 1 above)
Comment (lmcnulty) [reply site/gatsby-site/src/components/reports/ReportCard.js:57]: It adds a trailing slash `/cite/1/#r1/` which breaks the scrolling.
