### PR TITLE
Limit bulk send api calls to 10 per minute

### LINKED ISSUE #3332: Process notifications rate limit of 15 requests/min error
In the [last production build](https://github.com/responsible-ai-collaborative/aiid/actions/runs/12996686723/job/36249647119) we got this error:

### MailerSend error
```
body: 'Your account reached its rate limit of 15 requests/min. Please wait before trying again. #MS42903',
  statusCode: 429,
  message: '[Process Pending Notifications: Incidents Updates]: [Send Email]: undefined'
```

### PR DESCRIPTION
**Pull request by cesarvarela**
closes #3332

### CODE REVIEW

File: site/gatsby-site/server/emails/index.ts [hunk 1]
```diff
@@ -35,6 +36,12 @@ export const replacePlaceholdersWithAllowedKeys = (template: string, data: { [ke
     });
 }
 
+const bulkLimiter = new RateLimiter({
```
Comment (pdcp1) [inline site/gatsby-site/server/emails/index.ts:39]: Please add a comment explaining the reason for this limiter and something like:
```
// Allow 10 MailerSend API requests per minute
```

**Review by pdcp1 — CHANGES_REQUESTED** [review]

File: site/gatsby-site/server/emails/index.ts [hunk 2]
```diff
@@ -35,6 +36,15 @@ export const replacePlaceholdersWithAllowedKeys = (template: string, data: { [ke
     });
 }
 
+let bulkLimiter = new RateLimiter({
```
Comment (pdcp1) [inline site/gatsby-site/server/emails/index.ts:39]: Please add a comment with a link to the MailerSend documentation to know why we need to limit to 10 calls per second

File: site/gatsby-site/server/tests/emailRateLimit.spec.ts [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+}));
+
+describe("mailersendBulkSend with rate limiter", () => {
+
+    it("Allows only 10 calls per minute", async () => {
+
+        emails.setLimiter(new RateLimiter({
+            tokensPerInterval: 10,
+            interval: 2000,
+        }));
```
Comment (pdcp1) [inline site/gatsby-site/server/tests/emailRateLimit.spec.ts:22]: Do we need to set this limiter here as well?

**Review by pdcp1 — CHANGES_REQUESTED** [review]

File: site/gatsby-site/server/tests/emailRateLimit.spec.ts (hunk 3 above)
Comment (cesarvarela) [reply site/gatsby-site/server/tests/emailRateLimit.spec.ts:22]: It is so we don't have to wait a minute for the test to finish.

File: site/gatsby-site/server/emails/index.ts (hunk 2 above)
Comment (cesarvarela) [reply site/gatsby-site/server/emails/index.ts:39]: Added

**Review by pdcp1 — APPROVED** [review]

**Review by pdcp1 — CHANGES_REQUESTED** [review]
The test added failed https://github.com/responsible-ai-collaborative/aiid/actions/runs/13036774465/job/36369098297?pr=3336

**Review by pdcp1 — APPROVED** [review]
