### PR TITLE
Fix/expand card

### LINKED ISSUE #1572: Report card expand/collapse UX
The new report cards look good, but when you expand them the image abruptly disappears and you need to scroll all the way to the bottom of the article to collapse it again.

https://user-images.githubusercontent.com/25443411/215551185-c1a87c4f-cb5d-42a1-8732-2124bf7e1b6b.mp4

### PR DESCRIPTION
**Pull request by clari182**
- closed #1572

### CODE REVIEW

**Review by cesarvarela — COMMENTED** [review]
Sure this is not possible only with CSS?

**Comment by lmcnulty** [comment]
I think it looks weird to have the image bleed to the edge of the card when it's expanded. I was thinking either put the image inside the margins of that card (top) or have the full text slide out from the bottom of the card (bottom). I'm sorry if I was unclear before.

card-expand

**Review by cesarvarela — COMMENTED** [review]
- when expanding, the image shifts a little to the right
- when collapsing, the site seems to scroll randomly

**Comment by clari182** [comment]
@lmcnulty I went with the first option, let me know what you think.

File: site/gatsby-site/src/components/reports/ReportCard.js [hunk 1]
```diff
@@ -24,169 +24,214 @@ const ReportCard = ({ item, className = '', incidentId }) => {
...
-        <Image
-          className="img-fluid rounded-start h-full w-full max-w-full rounded-t-lg md:rounded-l-lg md:rounded-r-none border-r object-cover"
-          publicID={item.cloudinary_id ? item.cloudinary_id : `legacy/${md5(item.image_url)}`}
-          alt={item.title}
-          transformation={fill().height(480)}
-          itemIdentifier={t('Report {{report_number}}', {
-            report_number: item.report_number,
-          }).replace(' ', '.')}
-        />
+  const checkCardSize = () => {
```
Comment (lmcnulty) [inline site/gatsby-site/src/components/reports/ReportCard.js:37]: I don't think it's necessary for the image height to match the card height, so I think we can cut down on the JavaScript and state.

File: site/gatsby-site/src/components/reports/ReportCard.js [hunk 2]
```diff
@@ -24,169 +24,214 @@ const ReportCard = ({ item, className = '', incidentId }) => {
...
+              />
+            </Tooltip>
+          </div>
+          <div data-cy="variant-text_outputs" className="border-1 rounded-lg px-3">
+            <Markdown>{item.text_outputs}</Markdown>
           </div>
+        </div>
+      )}
+      <div className="flex justify-end mt-4">
+        <button
```
Comment (lmcnulty) [inline site/gatsby-site/src/components/reports/ReportCard.js:159]: It bother me that expanding the text makes the button to collapse it again move off-screen. What if we also made it so that clicking anywhere in the margins of the card would expand/collapse it?

**Review by lmcnulty — CHANGES_REQUESTED** [review]
image

File: site/gatsby-site/src/components/reports/ReportCard.js (hunk 2 above)
Comment (clari182) [reply site/gatsby-site/src/components/reports/ReportCard.js]: Done!

File: site/gatsby-site/src/components/reports/ReportCard.js (hunk 1 above)
Comment (clari182) [reply site/gatsby-site/src/components/reports/ReportCard.js]: Done!

**Comment by ShaurGaur** [comment]
image

I see in the deploy preview page [here](https://deploy-preview-1594--staging-aiid.netlify.app/cite/421/#r2444) that some of the images overflow the cards. 

For context, I'm using a 4K laptop screen.

**Comment by smcgregor** [comment]
@clari182 it looks like the overflow issue above occurs for some more unusual screen resolutions. I was able to replicate it by zooming in/out on my macbook screen. This is likely an issue for other people and needs a fix.

**Comment by clari182** [comment]
I was able to replicate also, I'll create an issue for this and assign it to myself.
