### PR TITLE
Fix tests for related reports

### LINKED ISSUE #1490: Fix related reports tests
Not sure if broken or simply outdated.

- Should show a list of related reports
- Should show a preliminary checks message
- Should show related reports based on semantic similarity
- Should not show semantically related reports when the text is under 256 non-space characters

### PR DESCRIPTION
**Pull request by clari182**
- closes #1490

### CODE REVIEW

File: site/gatsby-site/cypress/support/commands.js [hunk 1]
```diff
@@ -64,6 +64,7 @@ Cypress.Commands.add('setEditorText', (value, selector = '.CodeMirror') => {
   return cy
     .get(selector)
     .first()
+    .click()
```
Comment (cesarvarela) [inline site/gatsby-site/cypress/support/commands.js:67]: Does this make a difference?
