### PR TITLE
Fix/latest report link

### LINKED ISSUE #1692: Latest Report on landing goes to incident instead of report
"Latest Report" on landing page, should link to the report and not the whole incident

### PR DESCRIPTION
**Pull request by clari182**
- closes #1692

### CODE REVIEW

**Review by pdcp1 — APPROVED** [review]

File: site/gatsby-site/src/components/landing/LatestIncidentReport.js [hunk 1]
```diff
@@ -48,7 +61,7 @@ const LatestIncidentReport = ({ report }) => {
           </div>
           <div className="flex justify-end">
             <Link
```
Comment (cesarvarela) [inline site/gatsby-site/src/components/landing/LatestIncidentReport.js:63]: Should this use `LocalizedLink` too?

**Review by pdcp1 — APPROVED** [review]

**Review by pdcp1 — APPROVED** [review]
