### PR TITLE
Fix incident_id and duplicated entry in mongo

### LINKED ISSUE #2354: Edit Submission Form – Frozen "Adding as incident/issue ..."
Courtesy Danny:

> When adding a report to Incident 568, I clicked the "Add to incident 568" button. I click OK when the pop up asks me if I'm sure I want to add it. It kinda just freezes. It looks like this forever:
>  image

And:
> I've just run into the frozen promotion problem again with the "FTC investigates OpenAI over data leak and ChatGPT’s inaccuracy" report, which I'm filing as an issue report.
> image

### PR DESCRIPTION
**Pull request by clari182**
- closes #2354 
Test URL: https://deploy-preview-28--clarayoudale-staging.netlify.app/apps/submitted/

Ping me for login credentials if needed

### CODE REVIEW

**Comment by kepae** [comment]
Would you please add tests that would catch this bug in the future?
https://github.com/responsible-ai-collaborative/aiid/blob/0c0ec744c4216e79f019e99cae936749cea1e773/site/gatsby-site/cypress/e2e/unit/functions/promoteSubmissionToReport.cy.js

File: site/realm/functions/promoteSubmissionToReport.js [hunk 1]
```diff
@@ -121,21 +120,26 @@ exports = async (input) => {
         if (submission.user) {
           await subscriptionsCollection.insertOne({
             type: 'submission-promoted',
-            incident_id: BSON.Int32(newIncident.incident_id),
+            incident_id: BSON.Int32(parentIncident.incident_id),
```
Comment (kepae) [inline site/realm/functions/promoteSubmissionToReport.js:123]: Would you please add tests that would catch this bug in the future?
https://github.com/responsible-ai-collaborative/aiid/blob/0c0ec744c4216e79f019e99cae936749cea1e773/site/gatsby-site/cypress/e2e/unit/functions/promoteSubmissionToReport.cy.js

(commenting again to return the code review)

**Review by kepae — CHANGES_REQUESTED** [review]

**Review by kepae — APPROVED** [review]
(I love seeing deleted code ☠️)
