### PR TITLE
Fallback to EN if language is missing in doc, landingpage and posts

### LINKED ISSUE #2545: Blog – MDX + Prismic posts require all translations present to create pages
When creating a MDX-sourced blog post in `/blog` with the default lang `post_name.mdx` file, the absence of other languages' `post_name.[LANG].mdx` files for allowed languages causes errors. The error thrown is related to looking for the image file, but this issue goes away after providing the `fr` and `es` files.

We should be able to publish MDX posts even with only one .mdx file in any language.

e.g.:
* https://github.com/responsible-ai-collaborative/aiid/pull/2535

workflow build: https://github.com/responsible-ai-collaborative/aiid/actions/runs/7454131080/job/20280876233?pr=2535

```
error Truncated page data information for the failed page "/fr/blog/deepfakes-and-child-safety/": {
  "errors": {},
  "path": "/fr/blog/deepfakes-and-child-safety/",
  "slicesMap": {},
  "pageContext": {
    "slug": "/blog/deepfakes-and-child-safety",
    "frontmatter": {
      "title": "Deepfakes and Child Safety: A Survey and Analysis of 2023 Incidents and Responses",
      "metaTitle": "Deepfakes and Child Safety: A Survey and Analysis of 2023 Incidents and Responses",
      "metaDescription": "",
      "date": "2024-01-08",
      "image": "./images/image_doj",
      "author": "REDACT"
      "slug": "/blog/deepfakes-and-child-safety"
    },
    "locale": "fr",
    "hrefLang": "fr",
    "originalPath": "/blog/deepfakes-and-child-safety/",
    "dateFormat": "DD-MM-YYYY"
  }
}
failed Building static HTML for pages - 68.224s
error Building static HTML failed for path "/fr/blog/deepfakes-and-child-safety/"

  19 |   const postImage = mdx.frontmatter.image?.childImageSharp?.gatsbyImageData?.images?.fallback?.src;
  20 |   let metaImage = null;
> 21 |   if (postImage) {
     |                   ^
  22 |     metaImage = `${config.gatsby.siteUrl}${postImage}`;
  23 |   }
  24 |   const canonicalUrl = config.gatsby.siteUrl + props.location.pathname;
```

### PR DESCRIPTION
**Pull request by clari182**
Allows project to work when new language is set but not all docs and blog posts have been translated

- closes #2545

### CODE REVIEW

File: site/gatsby-site/src/templates/report.js [hunk 1]
```diff
@@ -24,8 +24,8 @@ function ReportPage(props) {
   const { loading, isRole } = useUserContext();
 
   if (report.language !== locale) {
-    report.title = data[locale].title;
-    report.text = data[locale].text;
+    report.title = data[locale]?.title || '';
```
Comment (pdcp1) [inline site/gatsby-site/src/templates/report.js:27]: I found a better way to fix this lack of translations for the report. Please take a look at this [PR](https://github.com/responsible-ai-collaborative/aiid/pull/2562/files)
In that way, we keep the default `title` and `text` instead of set to empty string.

File: site/gatsby-site/src/templates/post.js [hunk 2]
```diff
@@ -14,10 +14,14 @@ import { useLayoutContext } from 'contexts/LayoutContext';
...
 export default function Post(props) {
   const {
-    data: { mdx },
+    data: { mdx: localMdx, enMdx },
     children,
   } = props;
 
+  let mdx = localMdx;
+
+  if (!mdx) mdx = enMdx;
```
Comment (pdcp1) [inline site/gatsby-site/src/templates/post.js:23]: I personally prefer to write a new line on these `if` clauses. To avoid possible merge conflicts and keep consistency.
If you are OK, please change all PR files accordingly.

E.g: 
```
if (!mdx) {
  mdx = enMdx;
}
```

File: site/gatsby-site/src/templates/landingPage.js [hunk 3]
```diff
@@ -41,12 +41,12 @@ const LandingPage = (props) => {
...
     if (report.language !== language) {
-      const translation = data[`latestReports_${language}`].edges.find(
+      const translation = data[`latestReports_${language}`]?.edges.find(
         (translation) => translation.node.report_number === report.report_number
       );
 
-      report.title = translation.node.title;
-      report.text = translation.node.text;
+      report.title = translation?.node?.title || '';
+      report.text = translation?.node?.text || '';
```
Comment (pdcp1) [inline site/gatsby-site/src/templates/landingPage.js:49]: Please apply this [fix](https://github.com/responsible-ai-collaborative/aiid/blob/308cbfe72edfe86389222105af0cfd283e25e308/site/gatsby-site/src/templates/landingPage.js#L56C7-L61C8) instead

**Review by pdcp1 — CHANGES_REQUESTED** [review]

**Comment by pdcp1** [comment]
@clari182 How can I test this? Do you add a locale to your `.env` file and test it locally?

**Review by pdcp1 — CHANGES_REQUESTED** [review]

**Review by pdcp1 — CHANGES_REQUESTED** [review]

File: site/gatsby-site/cypress/e2e/unit/locale.cy.js [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+      'login.json',
+      'popovers.json',
+      'sponsors.json',
+      'submit.json',
+      'submitted.json',
+      'translation.json',
+      'validation.json',
+      'variants.json',
+      'wordcount.json',
+    ];
```
[the remark this answers is not in the document]
Comment (clari182) [reply site/gatsby-site/cypress/e2e/unit/locale.cy.js]: It's possible if I create a task to check if the file list matches depending on the locale

**Review by pdcp1 — APPROVED** [review]
