### PR TITLE
Remove description truncation to 200 chars, fix validation

### LINKED ISSUE #1201: Editor Submission Form – `description` gets cut off
For some reason, the description text was cut off from how it was written in the Submitter Form. Is there a legacy character limit for this description?

image

### PR DESCRIPTION
**Pull request by lmcnulty**
Resolves #1201.

### CODE REVIEW

File: site/gatsby-site/src/components/forms/SubmitForm.js [hunk 1]
```diff
@@ -104,14 +104,12 @@ const SubmitForm = () => {
...
 
-      const description = values.description ? values.description : values.text;
-
       const submission = {
         ...values,
         incident_id: values.incident_id == '' ? 0 : values.incident_id,
         date_submitted,
         date_modified: date_submitted,
-        description: description.substring(0, 200),
+        description: values.description || values.text,
```
Comment (cesarvarela) [inline site/gatsby-site/src/components/forms/SubmitForm.js:112]: I think this should be just `values.description`. Otherwise, when promoting to an incident, the `description` field will be huge.

File: site/gatsby-site/src/components/submissions/SubmissionForm.js [hunk 2]
```diff
@@ -48,13 +48,10 @@ export const schema = yup.object().shape({
...
     .max(500, "*Titles can't be longer than 500 characters")
     .required('*Title is required'),
-  description: yup.string().when(['_id', 'incident_id'], {
-    is: (_id, incident_id) => _id !== undefined && (incident_id == '' || incident_id === undefined),
-    then: yup
-      .string()
-      .min(3, 'Description must have at least 3 characters')
-      .max(500, "Description can't be longer than 500 characters"),
-  }),
+  description: yup
```
Comment (cesarvarela) [inline site/gatsby-site/src/components/submissions/SubmissionForm.js:51]: What's this change doing 🤔 ?

Comment (lmcnulty) [reply site/gatsby-site/src/components/submissions/SubmissionForm.js:51]: The description field is no longer required, so we don't need to check that there's no incident id to place a length restriction. Until I made this change, the validation messages were not showing up for the description field – not sure why.
