### PR TITLE
Fix table view report links

### LINKED ISSUE #2229: Improve report pages: Show page for each `/report/*`, regardless of incident associations
Currently, simple raw report pages are only generated for reports that are **not** associated with incidents.
For example, report 2973 generates a page at https://incidentdatabase.ai/reports/2973/ as it does not support a minted incidents (but rather exists as an *issue report*), but report 1 does not generate such a page(https://incidentdatabase.ai/reports/1/) because it is linked to an incident (https://incidentdatabase.ai/cite/1/).

This behavior may simply be because the report pages weren't prioritized, or because this is a built-in structure to avoid linking a report when an incident page should instead be the focus. However, if a report later becomes part of an incident, the report URL is now a dead end. (should it be that way? do protest.)

Creating a page for every report is also useful in the case where future discovery/explore features may surface reports independently of incidents (e.g. #2047). A useful page would also contain pointers to incidents that are based on the report.

Goals:
- [ ] every report URL endpoint results in a report page
- [ ] report pages surface connection/membership to the incident(s) they support

### PR DESCRIPTION
**Pull request by clari182**
- closes #2229 

The original idea was to have the report page for _all_ reports. But this is not possible due to the quantity of pages generated, the build fails because of insufficient space.

So, the fix here instead is when viewing reports on the table view (https://pr-2756--staging-aiid.netlify.app/apps/incidents/?view=reports) the report links to the cite page of that report.

### CODE REVIEW

**Comment by pdcp1** [comment]
@clari182 During my testing of https://pr-2756--staging-aiid.netlify.app/apps/incidents/?view=reports I realized that we have some timeout errors `502 502 Bad Gateway` on each `/graphql` call to retrieve the Live version of `reports` and Live version of `incidents`.

```
{"errorType":"LambdaTimeout","errorMessage":"2024-05-22T19:10:14.718Z afdded9a-fa1b-47d9-b13c-03372618773c Task timed out after 10.01 seconds"}
```

@cesarvarela Is this something related to the API changes? Or is this only happeninginn the Staging environment?

File: site/gatsby-site/src/components/reports/ReportCard.js [hunk 1]
```diff
@@ -143,23 +138,19 @@ const ReportCard = ({
...
           <div className="flex">
-            {reportTitle ? (
-              <>{reportTitle}</>
-            ) : (
-              <button
-                className="w-3/4 text-left"
-                onClick={toggleReadMore}
-                onKeyDown={toggleReadMoreKeyDown}
-              >
+            <Link to={`/reports/${item.report_number}`} className="hover:no-underline">
```
Comment (pdcp1) [inline site/gatsby-site/src/components/reports/ReportCard.js:141]: @clari182 Is this URL correct? When I navigate to https://pr-2756--staging-aiid.netlify.app/cite/658#r3803 and click on the report title, it redirects me to https://pr-2756--staging-aiid.netlify.app/reports/3803/ and it doesn't exist.

image

**Review by pdcp1 — CHANGES_REQUESTED** [review]

**Review by pdcp1 — APPROVED** [review]
