### PR TITLE
Fix/discover link break

### LINKED ISSUE #2501: Discover incident link breaks on view change
When changing the view type on the discover page the link to the incident changes and the incident ID is null: https://incidentdatabase.ai/cite/null/#r23

image

### PR DESCRIPTION
**Pull request by clari182**
- closes #2501 
https://pr-2537--staging-aiid.netlify.app

1. Go to Discover
2. Switch to list view
3. Click on a result

### CODE REVIEW

File: site/gatsby-site/src/components/discover/DisplayModeSwitch.js [hunk 1]
```diff
@@ -20,8 +21,42 @@ const modes = {
...
+        refinementList: {
+          ...previousState.refinementList,
+          display: [key],
+        },
+        configure: {
+          ...previousState.configure,
+        },
+      };
+
+      console.log(test);
```
Comment (pdcp1) [inline site/gatsby-site/src/components/discover/DisplayModeSwitch.js:46]: Please remove this `console.log()`

**Review by pdcp1 — CHANGES_REQUESTED** [review]
When I refresh this URL https://pr-2537--staging-aiid.netlify.app/apps/discover/?display=list&is_incident_report=true with the param `display=list` it doesn't set the `List` view as expected.

**Review by pdcp1 — APPROVED** [review]
