### PR TITLE
Fix Report edit form

### LINKED ISSUE #1280: Can't Update Report
I am not sure what is blocking me from updating the report found here: https://incidentdatabase.ai/cite/edit?report_number=1765

The button is not active and there is no apparent message indicating why. I successfully updated another report a moment ago, so there is something about this specific report. I think it needs some user-apparent error message so I will know what is necessary to change before it will allow me to submit the form.

### PR DESCRIPTION
**Pull request by pdcp1**
Closes #1280 

### Report/Submission Forms fixed
- Fix required fields on `/cite/edit` report form
- Fix required fields on `/apps/submitted` edit submission form
- Fix required fields on `/apps/submit` new submission form

### Testing link

https://deploy-preview-1292--staging-aiid.netlify.app

### CODE REVIEW

**Review by smcgregor — APPROVED** [review]

**Comment by smcgregor** [comment]
@cesarvarela this is blocking editing on a few things in prod, can you do a quick review?

CC @LKchemposer

File: site/gatsby-site/src/components/incidents/IncidentIdField.js [hunk 1]
```diff
@@ -11,6 +11,7 @@ export default function IncidentIdField({
   placeHolder = '',
   className = '',
   showIncidentData = true,
+  required = false,
```
Comment (cesarvarela) [inline site/gatsby-site/src/components/incidents/IncidentIdField.js:14]: I would also add validation in this component if this field is required (because as it is this property is only cosmetic), but it could be done in another PR

File: site/gatsby-site/src/components/submissions/SubmissionForm.js [hunk 2]
```diff
@@ -402,7 +411,17 @@ const SubmissionForm = () => {
...
         <details className="mt-3">
-          <summary data-cy="extra-fields">{t('Tell us more...')}</summary>
+          <summary data-cy="extra-fields">
+            {t('Tell us more...')}
+            {(errors['description'] ||
+              errors['developers'] ||
+              errors['deployers'] ||
+              errors['harmed_parties']) && (
+              <div className="text-red-500 pl-4">
+                <Trans ns="validation">Some data is missing.</Trans>
```
Comment (cesarvarela) [inline site/gatsby-site/src/components/submissions/SubmissionForm.js:421]: Of course, I'm guilty of this, but it is funny how we devs are bad at giving helpful error messages.

**Review by cesarvarela — APPROVED** [review]

File: site/gatsby-site/src/components/incidents/IncidentIdField.js (hunk 1 above)
Comment (pdcp1) [reply site/gatsby-site/src/components/incidents/IncidentIdField.js:14]: Agreed. The Incident ID field validation is currently handled by the yup schema.
There are two forms that are using the `<IncidentIdField>` component:

- `IncidentReportForm.js` with the Incident Id field required
```
incident_id: yup.number().positive().integer('*Must be an incident number').required()
```
- `SubmissionForm.js` with the Incident Id field not required
```
incident_id: yup.number().positive().integer('*Must be an incident number or empty')
```

File: site/gatsby-site/src/components/submissions/SubmissionForm.js (hunk 2 above)
Comment (pdcp1) [reply site/gatsby-site/src/components/submissions/SubmissionForm.js:421]: Yeah, I tried to let the user know that something is missing in a generic way on the `Tell me more...` section.
And if the user expands the section the explicit error messages are displayed.
