### PR TITLE
Fetch path from social media items

### LINKED ISSUE #2321: Fix RSS footer icon link
If the footer is getting from Prismic, the RSS icon link is not working.

image

I assume that this is because of the way that we store it on Prismic:

image

We should change that item to use the `url` field pointing to the Production RSS: https://incidentdatabase.ai/rss.xml

### PR DESCRIPTION
**Pull request by clari182**
- closes #2321

### CODE REVIEW

File: site/gatsby-site/src/components/layout/Footer.js [hunk 1]
```diff
@@ -48,6 +48,7 @@ export default function Footer() {
                 url {
                   url
                 }
+                path
```
Comment (pdcp1) [inline site/gatsby-site/src/components/layout/Footer.js:51]: Why do we need to add the `path` field? The `RSS` item is using the `path` field or the `url` field?

**Review by pdcp1 — CHANGES_REQUESTED** [review]

File: site/gatsby-site/src/components/layout/Footer.js (hunk 1 above)
Comment (clari182) [reply site/gatsby-site/src/components/layout/Footer.js:51]: RSS is using the path because it's not an external URL

**Review by pdcp1 — APPROVED** [review]
