### PR TITLE
Fix canonical urls

### LINKED ISSUE #1349: Canonical urls for mdx pages have trailing `/index`
Fortunately, that redirects to the parent url, so if search engines direct people there it will lead to the correct place.

image

### PR DESCRIPTION
**Pull request by lmcnulty**
Resolves #1349. Also adds canonical urls to pages where they were missing.

## Breakage Attempts / Testing

- In Spanish, check that the canonical url is correct for every page in the sidebar
  - **Found issue**: Still missing from /taxonomies. Fixed.
  - **Found issue**: Still missing from /blog, along with Helmet generally. Fixed.
- Check /taxonomies/cset
  - **Found issue**: Whole helmet is still missing. Fixed.
- Check /entities/facebook
  - **Found issue**: Whole helmet is still missing. Fixed.
- Check every page linked in the footer
  - **Found issue**: canonical url for `research/related-work` is `research/4-related-word`. Changed url to include number, matching the others research pages.

### CODE REVIEW

File: site/gatsby-site/src/pages/account.js [hunk 1]
```diff
@@ -15,7 +16,7 @@ const Account = (props) => {
 
   return (
     <Layout {...props}>
-      <AiidHelmet>
+      <AiidHelmet canonicalUrl={config.gatsby.siteUrl + '/account'}>
```
Comment (cesarvarela) [inline site/gatsby-site/src/pages/account.js:19]: It looks like  `config.gatsby.siteUrl` could be inside `AiidHelmet` 🤔

Comment (lmcnulty) [reply site/gatsby-site/src/pages/account.js]: Good point. Fixed!

**Comment by cesarvarela** [comment]
@lmcnulty please fix conflics
