### PR TITLE
Fix CSET tool merge

### LINKED ISSUE #2268: CsetTool merge broken
From Mia:

> Hi everyone! I am having some issues with the reconciliation tool: when I click on Merge Classification the button keeps buffering. A small red popup appears stating that classifications have been merged, but when I go back to the incident page the reconciled annotation (CSETv1) does not appear.

### PR DESCRIPTION
**Pull request by lmcnulty**
Resolves #2268.

### CODE REVIEW

File: site/gatsby-site/src/components/classifications/CsetTable.js [hunk 1]
```diff
@@ -435,7 +435,7 @@ export default function CsetTable({ data, taxa, incident_id, ...props }) {
       setSubmitting(false);
     } catch (error) {
       addToast({
-        message: 'Classification updated',
+        message: 'Could not update classification',
```
Comment (kepae) [inline site/gatsby-site/src/components/classifications/CsetTable.js:438]: Good catch!

**Review by kepae — APPROVED** [review]
I'll merge these after we can test the deploy preview.

**Review by kepae — CHANGES_REQUESTED** [review]
Could you also update the tests?

```
12:02:01 PM:   Running:  integration/apps/csettool.cy.js                                               (40 of 62)
12:02:03 PM: 
12:02:03 PM:   CSET tool
12:02:15 PM:     (Attempt 1 of 3) Successfully loads CSET annotator classifications
12:02:30 PM:     (Attempt 2 of 3) Successfully loads CSET annotator classifications
12:02:51 PM:     1) Successfully loads CSET annotator classifications
12:02:51 PM:   0 passing (48s)
12:02:51 PM:   1 failing
12:02:51 PM:   1) CSET tool
12:02:51 PM:        Successfully loads CSET annotator classifications:
12:02:51 PM:       AssertionError: expected { Object (notes, attributes, ...) } to deeply equal { Object (incidents, reports, ...) }
12:02:51 PM:       + expected - actual
12:02:51 PM:       -{ notes: 'Annotator 1: \n\n This a note from the annotator 1\n\nAnnotator 2: \n\n This a note from the annotator 2',
12:02:51 PM:       +{ incidents: { link: [ 52 ] },
12:02:51 PM:       +  reports: [],
12:02:51 PM:       +  namespace: 'CSETv1',
12:02:51 PM:       +  notes: 'Annotator 1: \n\n This a note from the annotator 1\n\nAnnotator 2: \n\n This a note from the annotator 2',
12:02:51 PM:          attributes:
12:02:51 PM:           [ { short_name: 'Incident Number', value_json: '52' },
12:02:51 PM:             { short_name: 'Quality Control', value_json: 'true' },
12:02:51 PM:             { short_name: 'Physical Objects', value_json: 'yes' },
12:02:51 PM: --
12:02:51 PM:               value_json: '[navigation,transportation]' },
12:02:51 PM:             { short_name: 'AI tools and methods',
12:02:51 PM:               value_json: '[Autonomous Driving]' },
12:02:51 PM:             { short_name: 'Notes (AI Functionality and Techniques)',
12:02:51 PM:       -       value_json: '' } ],
12:02:51 PM:       -  namespace: 'CSETv1',
12:02:51 PM:       -  incidents: { link: [ 52 ] },
12:02:51 PM:       -  reports: { link: [] } }
12:02:51 PM:       +       value_json: '' } ] }
12:02:51 PM:       
```

**Review by kepae — APPROVED** [review]
